# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(AZURE_OAUTH_CLIENT_ID)%'
            client_secret: '%env(AZURE_OAUTH_CLIENT_SECRET)%'
            redirect_route: connect_azure_check
            redirect_params: {}
            resource: https://graph.microsoft.com/
