version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###


###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"  # Port sur lequel Symfony va envoyer les e-mails
      - "1080:1080"
###< symfony/mailer ###
