version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_gestion
    ports:
      - '3307:3306'
  ###< doctrine/doctrine-bundle ###

  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - '8025:8025'  # Web UI port
  #     - '1025:1025'  # SMTP port

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
