connect_azure_check:
    path: /connect/azure/check
    controller: 'KnpU\OAuth2ClientBundle\Controller\OAuth2ClientController::connectCheckAction'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_gestion_attribution_signature:
    path: '/gestion/attribution/{id}/signature'
    controller: 'App\Controller\PdfGeneratorController::signature'
    methods: ['GET']
    requirements:
        id: '\d+'

user_gestion_attribution_save_signature:
    path: '/gestion/attribution/{id}/signature/save-signature'
    controller: 'App\Controller\PdfGeneratorController::saveSignature'
    methods: ['POST']
    requirements:
        id: '\d+'